### ISSUE TITLE
Value 

### ISSUE THREAD

**Issue by kikirizki** [mypetyak/StrokeWidthTransform#2]
Error value:more than one value to unpack

**Comment by lxdatgithub** [comment]
run the swt.py
output:
'
    SWTS  
    []  
    DONESWTS  
    Traceback (most recent call last):  
    File "swt.py", line 371, in <module>  
    final_mask = SWTScrubber.scrub(local_filename)  
    File "swt.py", line 32, in scrub  
    word_images = cls._find_words(swts, heights, widths, topleft_pts, images)  
    File "swt.py", line 296, in _find_words  
    swt_tree = scipy.spatial.KDTree(np.asarray(swts))  
    File "~/anaconda2/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 235, in __init__  
    self.n, self.m = np.shape(self.data)  
    ValueError: need more than 1 value to unpack  
'

cannot know why

**Comment by truongtd6285** [comment]
can see here: [https://stackoverflow.com/questions/28551279/error-running-scipy-kdtree-example](url)

**Comment by lovebobo** [comment]
I meet the same problem,the above link is invalid,can someone else offer anther one? thx!

**Comment by truongtd6285** [comment]
i don't know how the embed link doesn't work, you can copy & paste above link to web browser to see.

**Comment by lovebobo** [comment]
thx every much!! But I still can not run this code sucesseful. Because the "swt = cls._swt(theta, canny, sobelx, sobely)"  return a NULL value which cause the above problem.

**Comment by truongtd6285** [comment]
run debug and check your input data again, it should run well.

**Comment by QaisarRajput** [comment]
The issue persists. and by debugging i found out the lines which have issues

        // This line returns a 2D-array. where all values are 
        // np.Infinity. Hence this issue propagate to other functions too. i.e the line below where shapes 
        // dict is empty
        swt = cls._swt(theta, canny, sobelx, sobely) 
        shapes = cls._connect_components(swt)

Now by looking inside the `swt` function, the main variable swt is initialized with np.Infinity. which i think is supposed to change in the code below. but no change is happening to the swt 2D-array. i checked at the end of that function `(swt==np.Infinity).all()` which returned **True**
Any idea what is happening here?

**Comment by QaisarRajput** [comment]
One different thing is, i am using OpenCV 3.1.0. if that by chance has anything to do with it

**Comment by bhanga-manish** [comment]
@QaisarRajput Did you managed to solve this error?

**Comment by truongtd6285** [comment]
You got the problem from the beginning of program, so i guess that your input data for the function _swt(theta, canny, sobelx, sobely) was wrong somewhere. You see lines:
`if diagnostics:
            cv2.imwrite('edges.jpg',edges)
            cv2.imwrite('sobelx64f.jpg', np.absolute(sobelx64f))
            cv2.imwrite('sobely64f.jpg', np.absolute(sobely64f))
            # amplify theta for visual inspection
            theta_visible = (theta + np.pi)*255/(2*np.pi)
cv2.imwrite('theta.jpg', theta_visible)`

you simply set "diagnostics = True" at line 16 and will see what function _create_derivative output (images: edges.jpg, sobelx64f.jpg, sobely64f.jpg, theta.jpg)

**Comment by michaelcwang2** [comment]
I tried several case and it looked to me the _swt method always made either rays or layers for shapes input zero list. those diagnostics files were there but swt.jpg would always looks empty.

**Comment by truongtd6285** [comment]
May be your input data was empty? Look at the ending part of code and replace 
`file_url = 'http://upload.wikimedia.org/wikipedia/commons/0/0b/ReceiptSwiss.jpg
local_filename = hashlib.sha224(file_url).hexdigest()` 
by one jpg file on your local computer. 
You can read my comments here and try with the version i uploaded: [https://github.com/mypetyak/StrokeWidthTransform/issues/1]. Hope it helps.

**Comment by michaelcwang2** [comment]
Hi @truongtd6285 
I tried #1 but a strange thing there and needed to figure out. Originally I didn't Canny the picture from weblink but directly call class on a local image file but error happened on _create_derivative by "Assertion Failed", then I went back to the original code and the output would be always SWT on that local image file and return the same result as original git of mypetyak's one. Would you advise possible cause so I can keep debugging, thank you.

**Comment by ZhaoJunxin** [comment]
The problem cause by the type of cur_x and cur_y are float in _swt function.
So the program will into the exception every time and get a empty swt image.
Solution:
```
      cur_x = int(math.floor(x + grad_x * i))
      cur_y = int(math.floor(y + grad_y * i))
```
